services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.6
    container_name: keycloak-auth2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
    command: start-dev
  app:
    image: node:24
    container_name: auth-app
    working_dir: /app
    environment:
      - APP_PORT=3000
      - KC_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3JZKkuGJsGXrwBpziXpu4UMk31nejSPuTQ4GwmwhyPfFkqnBAdSXF5xxtkHwTWpQYVw8QCnmyDartAvyxcEE8GAJMSae4hg/nk1yQZnhZEhEzdx76oZHMwNtZUYENosq1761a3Wbe9AL8ijQwdrT0Uov+l0lkG7Gcr+A6ocpX/je6tQY6bZX4KjIHRVRTnJ7bIQnkrVfs0sY6Exi0+PLhCKX0s1J8gAV8xp7bflVV0X2405BQjHdmz4TXNTOBA3iMGz7aIO5695CHiOIisftNdLoVjrgh6xpHZ/Z6qTnnfwFEdNYDl8+HbCmoJciFjfNmXVuwvZzXfIsQMhdYYCB5wIDAQAB
      - KC_REALM=master
      - KC_CLIENT_ID=auth-app
      - KC_SERVER_URL=http://keycloak:8080/auth
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev